server:
  port: ${SERVER_PORT}

spring:
  config:
    activate:
      on-profile: dev

  application:
    name: fhk-ticketing-movie-service

  datasource:
    password: ${DB_PW}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USER}
    url: ${DB_URL}

  jpa:
    properties:
      hibernate.id.sequence.increment_size: 1   # allocation 1로 설정,  prod 프로필에서는 50 권장
      hibernate:
        default_batch_fetch_size: '1000'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect

  data:
    redis:
      password: ${REDIS_PW}
      port: '16379'
      host: 192.168.0.184

jwt:
  verifier: # JWT 인증시 사용
    public-key-path: classpath:keys/jwt-public.pem

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

