apiVersion: v1
kind: Service
metadata:
  name: fhk-ticketing-payment-service
  namespace: prod
  labels:
    app: fhk-ticketing-payment-service
    env: prod
spec:
  type: ClusterIP
  selector:
    app: fhk-ticketing-payment-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
