apiVersion: v1
kind: Service
metadata:
  name: fhk-ticketing-member-service
  namespace: staging
  labels:
    app: fhk-ticketing-member-service
    env: staging
spec:
  type: ClusterIP
  selector:
    app: fhk-ticketing-member-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
