server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${DB_URL:jdbc:mariadb://192.168.45.210:3306/fhk_ticketing_reservation_db}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        id:
          sequence:
            increment_size: ${SQL_INCREMENT_SIZE:50}

logging:
  level:
    root: info
    org.hibernate.SQL: warn
    org.hibernate.type.descriptor.sql: warn
